//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoggingTracker.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JoggingTracker.Localization.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied..
        /// </summary>
        public static string ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Jogging Record.
        /// </summary>
        public static string ADD_JOGGING_RECORD {
            get {
                return ResourceManager.GetString("ADD_JOGGING_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter again your new password.
        /// </summary>
        public static string CONFIRM_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your current password.
        /// </summary>
        public static string CURRENT_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("CURRENT_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth required.
        /// </summary>
        public static string DOB_REQUIRED {
            get {
                return ResourceManager.GetString("DOB_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Jogging Record.
        /// </summary>
        public static string EDIT_JOGGING_RECORD {
            get {
                return ResourceManager.GetString("EDIT_JOGGING_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name required.
        /// </summary>
        public static string FIRST_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("FIRST_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid current password..
        /// </summary>
        public static string INVALID_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date range !.
        /// </summary>
        public static string INVALID_DATE_RANGE {
            get {
                return ResourceManager.GetString("INVALID_DATE_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid distance !.
        /// </summary>
        public static string INVALID_DISTANCE {
            get {
                return ResourceManager.GetString("INVALID_DISTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogging distance required..
        /// </summary>
        public static string JOGGING_DISTANCE_REQUIRED {
            get {
                return ResourceManager.GetString("JOGGING_DISTANCE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogging end date/time required.
        /// </summary>
        public static string JOGGING_END_DATETIME_REQUIRED {
            get {
                return ResourceManager.GetString("JOGGING_END_DATETIME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogging start date/time required.
        /// </summary>
        public static string JOGGING_START_DATETIME_REQUIRED {
            get {
                return ResourceManager.GetString("JOGGING_START_DATETIME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name required.
        /// </summary>
        public static string LAST_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("LAST_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new password.
        /// </summary>
        public static string NEW_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("NEW_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not match..
        /// </summary>
        public static string PASSWORD_NOT_MATCH {
            get {
                return ResourceManager.GetString("PASSWORD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        public static string PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete! Record referenced by other element..
        /// </summary>
        public static string RECORD_REFERENCED_BY_OTHER_ELEMENT {
            get {
                return ResourceManager.GetString("RECORD_REFERENCED_BY_OTHER_ELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. We are not able to process your reqeust..
        /// </summary>
        public static string UNABLE_PROCESS_YOUR_REQUEST {
            get {
                return ResourceManager.GetString("UNABLE_PROCESS_YOUR_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exist !.
        /// </summary>
        public static string USER_NAME_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("USER_NAME_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name required.
        /// </summary>
        public static string USER_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("USER_NAME_REQUIRED", resourceCulture);
            }
        }
    }
}
